BrandName = "Gnu"
Season = "W2022_2023"

[Snowboards.MEN]

Riders = "MEN"

Urls = [
    "https://www.gnu.com/money",
    "https://www.gnu.com/head-space",
    "https://www.gnu.com/head-space-x-worble",
    "https://www.gnu.com/4x4",
    "https://www.gnu.com/gwo",
    "https://www.gnu.com/finest",
    "https://www.gnu.com/riders-choice",
    "https://www.gnu.com/rc-c3",
    "https://www.gnu.com/banked-country",
    "https://www.gnu.com/banked-country-split",
    "https://www.gnu.com/antigravity",
    "https://www.gnu.com/essential-service",
    "https://www.gnu.com/gremlin",
    "https://www.gnu.com/gremlin-x-airblaster",
    "https://www.gnu.com/hyper",
    "https://www.gnu.com/gorp-split",
]

[Snowboards.WOMEN]

Riders = "WOMEN"

Urls = [
    "https://www.gnu.com/b-nice",
    "https://www.gnu.com/free-spirit",
    "https://www.gnu.com/chromatic",
    "https://www.gnu.com/ladies-choice",
    "https://www.gnu.com/pro-choice",
    "https://www.gnu.com/gloss",
    "https://www.gnu.com/barrett-split",
    "https://www.gnu.com/barrett",
    "https://www.gnu.com/velvet",
    "https://www.gnu.com/ravish",
]

[Snowboards.YOUTH]

Riders = "YOUTH"

Urls = [
    "https://www.gnu.com/recess",
    "https://www.gnu.com/young-money",
]